- hosts: localhost
  tasks:
  - name: Create a new user in ManageIQ
    manageiq_user:
     userid: "{{ user }}"
     password: "{{ password }}"
     name: "{{ fname }}"
     group: 'EvmGroup-user'
     email: '{{ user }}@example.com'
     manageiq_connection:
      url: 'http://127.0.0.1:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
