- hosts: localhost
  tasks:
  - name: Create a new user in ManageIQ
    manageiq_user:
     userid: "{{ dialog_user }}"
     password: "{{ dialog_password }}"
     name: "{{ dialog_fname }}"
     group: 'EvmGroup-user'
     email: '{{ dialog_user }}@example.com'
     manageiq_connection:
      url: 'http://127.0.0.1:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
